# Generated by Django 5.2.15 on 2026-06-18 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaxSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_code', models.CharField(max_length=50, verbose_name='蜡样编号')),
                ('cup_type', models.CharField(max_length=50, verbose_name='杯型')),
                ('fragrance_code', models.CharField(max_length=50, verbose_name='香型代号')),
                ('wick_spec', models.CharField(max_length=50, verbose_name='芯线规格')),
                ('test_batch', models.CharField(max_length=50, verbose_name='测试批次')),
                ('responsible_person', models.CharField(max_length=50, verbose_name='责任人')),
                ('status', models.CharField(choices=[('pending_proofing', '待打样'), ('pending_test', '待测试'), ('in_test', '测试中'), ('pending_retest', '待复测'), ('need_reform', '需改配'), ('version_ready', '可归入版本库')], default='pending_proofing', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remarks', models.TextField(blank=True, default='', verbose_name='备注')),
            ],
            options={
                'verbose_name': '蜡样',
                'verbose_name_plural': '蜡样',
                'ordering': ['-created_at'],
                'unique_together': {('test_batch', 'sample_code')},
            },
        ),
        migrations.CreateModel(
            name='BurnTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_round', models.PositiveIntegerField(default=1, verbose_name='测试轮次')),
                ('is_retest', models.BooleanField(default=False, verbose_name='是否复测')),
                ('ignite_time', models.DateTimeField(verbose_name='点燃时间')),
                ('extinguish_time', models.DateTimeField(blank=True, null=True, verbose_name='熄灭时间')),
                ('melt_pool_diameter', models.FloatField(blank=True, null=True, verbose_name='熔池直径(cm)')),
                ('smoke_level', models.IntegerField(blank=True, choices=[(1, '1级-无烟'), (2, '2级-轻微'), (3, '3级-中等'), (4, '4级-偏高'), (5, '5级-严重')], null=True, verbose_name='烟量等级')),
                ('cup_wall_temp', models.FloatField(blank=True, null=True, verbose_name='杯壁温度(℃)')),
                ('abnormal_desc', models.TextField(blank=True, default='', verbose_name='异常描述')),
                ('retest_suggestion', models.TextField(blank=True, default='', verbose_name='复测建议')),
                ('enter_next_round', models.BooleanField(blank=True, null=True, verbose_name='是否进入下一轮')),
                ('test_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('tested_by', models.CharField(blank=True, default='', max_length=50, verbose_name='测试人')),
                ('auto_flags', models.JSONField(blank=True, default=dict, verbose_name='自动识别标记')),
                ('wax_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='burn_tests', to='samples.waxsample', verbose_name='蜡样')),
            ],
            options={
                'verbose_name': '燃烧测试记录',
                'verbose_name_plural': '燃烧测试记录',
                'ordering': ['-test_time'],
            },
        ),
    ]
