# Generated by Django 5.2.15 on 2026-06-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WickProblemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wick_spec', models.CharField(max_length=50, verbose_name='芯线规格')),
                ('test_batch', models.CharField(max_length=50, verbose_name='测试批次')),
                ('problem_count', models.PositiveIntegerField(default=0, verbose_name='问题记录数')),
                ('affected_samples', models.JSONField(blank=True, default=list, verbose_name='涉及蜡样')),
                ('last_triggered', models.DateTimeField(auto_now=True, verbose_name='最后触发时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('resolved', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('note', models.TextField(blank=True, default='', verbose_name='处理备注')),
            ],
            options={
                'verbose_name': '芯线问题集中告警',
                'verbose_name_plural': '芯线问题集中告警',
                'ordering': ['-last_triggered'],
                'unique_together': {('wick_spec', 'test_batch')},
            },
        ),
    ]
