# Generated by Django 5.2.15 on 2026-06-18 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_wickproblemalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetestClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('continue_retest', '继续复测'), ('transfer_reform', '转入改配'), ('confirm_version', '确认可归入版本库')], max_length=30, verbose_name='处理结论')),
                ('handler', models.CharField(blank=True, default='', max_length=50, verbose_name='处理人')),
                ('remark', models.TextField(blank=True, default='', verbose_name='处理备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='处理时间')),
                ('burn_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closures', to='samples.burntest', verbose_name='关联测试记录')),
                ('wax_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retest_closures', to='samples.waxsample', verbose_name='蜡样')),
            ],
            options={
                'verbose_name': '复测闭环处理记录',
                'verbose_name_plural': '复测闭环处理记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
