# Generated by Django 5.2.15 on 2026-06-18 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_retestclosure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wickproblemalert',
            name='problem_count',
            field=models.PositiveIntegerField(default=0, verbose_name='问题样品数'),
        ),
        migrations.CreateModel(
            name='RetestPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_no', models.CharField(max_length=50, unique=True, verbose_name='计划编号')),
                ('plan_status', models.CharField(choices=[('planned', '待执行'), ('in_progress', '执行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='planned', max_length=20, verbose_name='计划状态')),
                ('planned_retest_time', models.DateTimeField(verbose_name='计划复测时间')),
                ('responsible_person', models.CharField(max_length=50, verbose_name='负责人')),
                ('retest_goal', models.TextField(blank=True, default='', verbose_name='复测目标')),
                ('attention_notes', models.TextField(blank=True, default='', verbose_name='注意事项')),
                ('source_reason', models.CharField(choices=[('abnormal_test', '测试异常待复测'), ('need_reform', '需改配后复测'), ('manual_initiated', '手动发起复测'), ('history_issue', '历史问题回顾'), ('quality_audit', '质量抽检复核'), ('other', '其他原因')], default='abnormal_test', max_length=30, verbose_name='来源原因')),
                ('source_reason_detail', models.TextField(blank=True, default='', verbose_name='原因说明')),
                ('created_by', models.CharField(blank=True, default='', max_length=50, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cancelled_reason', models.TextField(blank=True, default='', verbose_name='取消原因')),
                ('source_burn_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_plans', to='samples.burntest', verbose_name='关联异常测试记录')),
                ('wax_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retest_plans', to='samples.waxsample', verbose_name='蜡样')),
            ],
            options={
                'verbose_name': '复测计划',
                'verbose_name_plural': '复测计划',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RetestPlanExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_retest_time', models.DateTimeField(verbose_name='实际复测时间')),
                ('executed_by', models.CharField(blank=True, default='', max_length=50, verbose_name='执行人')),
                ('result_description', models.TextField(blank=True, default='', verbose_name='结果说明')),
                ('closure_action', models.CharField(blank=True, choices=[('continue_retest', '继续复测'), ('transfer_reform', '转入改配'), ('confirm_version', '确认可归入版本库')], max_length=30, null=True, verbose_name='处理结论')),
                ('closure_remark', models.TextField(blank=True, default='', verbose_name='处理备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('burn_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_executions', to='samples.burntest', verbose_name='关联复测记录')),
                ('retest_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='samples.retestplan', verbose_name='复测计划')),
            ],
            options={
                'verbose_name': '复测执行记录',
                'verbose_name_plural': '复测执行记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
